exports.fancyFridayDemos = [
  { url: 'https://toolness.makes.org/thimble/poundsplat',
    contentType: 'application/x-thimble',
    contenturl: 'https://toolness.makes.org/thimble/poundsplat_',
    locale: 'en_US',
    title: 'Poundsplat',
    description: 'Fancy friday demo microgame 3',
    author: '',
    published: true,
    tags: 
     [ 'twitter-author%3Astenington',
       'microgame',
       'fancy-friday-demo' ],
    thumbnail: 'https://webmaker.org/img/thumbs/thimble-grey.png',
    remixedFrom: null,
    likes: [],
    reports: [],
    remixurl: 'https://toolness.makes.org/thimble/poundsplat/remix',
    editurl: 'https://toolness.makes.org/thimble/poundsplat/edit',
    _id: '52a23bc31b246cad69000159',
    createdAt: 1386363843077,
    updatedAt: 1386363843077,
    username: 'toolness',
    emailHash: 'b6c1ebb35d0c41dfe0728dd0dc6ae5b1' },
  { url: 'https://toolness.makes.org/thimble/flyswat',
    contentType: 'application/x-thimble',
    contenturl: 'https://toolness.makes.org/thimble/flyswat_',
    locale: 'en_US',
    title: 'Flyswat',
    description: 'Example Fancy Friday microgame 1',
    author: '',
    published: true,
    tags: [ 'fancy-friday-demo', 'microgame' ],
    thumbnail: 'https://webmaker.org/img/thumbs/thimble-grey.png',
    remixedFrom: null,
    likes: [],
    reports: [],
    remixurl: 'https://thimble.webmaker.org/project/25650/remix',
    editurl: 'https://thimble.webmaker.org/project/25650/edit',
    _id: '528be2aa70e23ec85d0000df',
    createdAt: 1384899242486,
    updatedAt: 1394808824710,
    username: 'toolness',
    emailHash: 'b6c1ebb35d0c41dfe0728dd0dc6ae5b1' },
  { url: 'https://toolness.makes.org/thimble/typetheword',
    contentType: 'application/x-thimble',
    contenturl: 'https://toolness.makes.org/thimble/typetheword_',
    locale: 'en_US',
    title: 'Type-The-Word',
    description: 'Fancy Friday example microgame 2',
    author: '',
    published: true,
    tags: 
     [ 'fancy-friday-demo',
       'microgame',
       'twitter-author%3Aepchristensen' ],
    thumbnail: 'https://webmaker.org/img/thumbs/thimble-grey.png',
    remixedFrom: null,
    likes: [],
    reports: [],
    remixurl: 'https://toolness.makes.org/thimble/typetheword/remix',
    editurl: 'https://toolness.makes.org/thimble/typetheword/edit',
    _id: '528be36fa207c680400000d1',
    createdAt: 1384899439095,
    updatedAt: 1386363337505,
    username: 'toolness',
    emailHash: 'b6c1ebb35d0c41dfe0728dd0dc6ae5b1' }
];
